### ISSUE TITLE
Decoder does not handle type "object"

### ISSUE THREAD

**Issue by bkhouri** [sunng87/pyclj#15]
I have a response that returns the following syntax

`#object[<namespace>.<record> <hex_number> "<edn>"]`

However, calling `clj.loads(data)` fails with the following:

    >>> clj.loads(data)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/site-packages/clj.py", line 407, in loads
        result = load(buf)
      File "/usr/lib/python2.7/site-packages/clj.py", line 403, in load
        return decoder.decode()
      File "/usr/lib/python2.7/site-packages/clj.py", line 82, in decode
        v = self.__read_token()
      File "/usr/lib/python2.7/site-packages/clj.py", line 263, in __read_token
        raise ValueError('Unexpected char: "%s" at line %d, col %d' % (c, self.cur_line, self.cur_pos))
    ValueError: Unexpected char: "#" at line 1, col 1

It would be nice to handle the type `object`.

**Comment by sunng87** [comment]
Yes this is true, object/record were no supported in this library. Because we cannot find `com.example.funktown.DoubleEntity` type on the python side. Perhaps you can transform your clojure object to a map before given it to python.

**Comment by bkhouri** [comment]
The `object` seems to have the same structure.  

  #object[<namespace> <hex> "<edn>"]  

If we receive #object, why not just ignore the next `[`, then ignore the `<namespace>` and `<hex>`.  Then return the `EDN` object as a dictionary and ignore the `]`?
