### ISSUE TITLE
No module named 'cStringIO'

### ISSUE THREAD

**Issue by trevor** [sunng87/pyclj#5]
``` python
>>> import clj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.3/site-packages/clj.py", line 47, in <module>
    from cStringIO import StringIO
ImportError: No module named 'cStringIO'
```

**Comment by mudimbamoonde** [comment]
try:
 import  cStringIO
except Exception as e:
   import sys

**Comment by bkhouri** [comment]
is there an ETA on when this package will support python3?

**Comment by trevor** [comment]
@bkhouri https://github.com/swaroopch/edn_format is actively being developed
